function dy = predSIM(t,y,s)

% predSIM: computes the derivatives involved in solving a system of ODEs
% which describe the position and orientation of a rigid body. This
% simulates a fish swimming through water.  
%
% The glabal variale 's' is a structure with parameter values
% 
% The inputs (t,y,s) are fed into fin_kine, which then outputs the lift
% vector generated by the motion of the fin and and updated structure 's'

% global s

% Components of drag on body
drag_x  = - 0.5*s.cDrag*s.rho*s.SA*(sqrt(y(2)^2 + y(4)^2))*y(2);
drag_y  = - 0.5*s.cDrag*s.rho*s.SA*(sqrt(y(2)^2 + y(4)^2))*y(4);
drag_theta  = - s.SA*s.rho*y(6)*abs(y(6));
% drag_theta  = - 0.5*s.cDrag_rot*y(6)*abs(y(6));

% Lift generated by fin, given in (x,y) components inertial FOR
[s,lift,torque,finVel] = fin_kine(s,y,(t-s.tCurr));

% Preallocate derivative vector for system of equations
dy = zeros(8,1);

% Equations for x-coordinate 
dy(1) = y(2);
dy(2) = (lift(:,1) + drag_x) ./ s.mass;

% Equations for y-coordinate 
dy(3) = y(4);
dy(4) = (lift(:,2) + drag_y) ./ s.mass;

% Equations for theta (assume COM of body is anterior to its midpoint)
dy(5) = y(6);
dy(6) = (torque + drag_theta) ./ (s.bodyI);

% Fin velocity (so that fin position is returned by the solution)
dy(7) = finVel(:,1);
dy(8) = finVel(:,2);
end


